<?php
/**
 * 
 * @category  design
 * @package   insale_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script type="text/javascript">
(function(d){
  var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
  p.type = 'text/javascript';
  p.async = true;
  p.src = '//assets.pinterest.com/js/pinit.js';
  f.parentNode.insertBefore(p, f);
}(document));
</script>

<?php 
$css_font1 = Mage::getStoreConfig('insale/general/googlefonts');
$css_font2 = Mage::getStoreConfig('insale/general/googlefonts2');
$css_color1 = Mage::getStoreConfig('insale/general/color1');
$css_color2 = Mage::getStoreConfig('insale/general/color2');
$css_color3 = Mage::getStoreConfig('insale/general/color3');
?>
<?php if ($css_font1 != 'Default'): ?>
    <link href='http://fonts.googleapis.com/css?family=<?php echo $css_font1;?>:100,200,300,400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <style type="text/css">
        body
        { 
            font-family: <?php echo Mage::getStoreConfig('insale/general/googlefonts');?>,Arial, Helvetica, sans-serif;
        }
    </style>
<?php endif;?>
    
<?php if ($css_font2 != 'Default'): ?>
    <link href='http://fonts.googleapis.com/css?family=<?php echo $css_font2;?>:100,200,300,400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <style type="text/css">
        .promo-banner .promo-text,
        .view-more-link,
        .box-up-sell header h2,
        .products-list li.item .actions,
        .actions button.btn-cart,
        .products-list li.item .actions .btn-cart,
        .ajaxcart-product-message,
        .nav-container #main .menu-footer a,
        .no-products,
        .ajaxcart-loading,
        .website-header .header-bottom .cart .dropdown-content .subtotal,
        .nav-container #menu,
        .promo-divider span
        { 
            font-family: <?php echo Mage::getStoreConfig('insale/general/googlefonts2');?>;
        }
    </style>
<?php endif;?>

<style type="text/css">
    /* FIRST COLOR*/
    #toTop,
    .actions button.btn-cart span.btn-cart-icon,
    .account-login .page-title .page-icon, 
    .account-create .page-title .page-icon,
    .i-pager,
    .link-wishlist-icon,
    .link-compare-icon,
    .email-friend-icon,
    .btn-remove,
    .website-header-scroll,
    .website-header .header-bottom .content-triangle,
    .products-grid .product-item-detailed .link-wishlist-icon,
    .products-grid .product-item-detailed .link-compare-icon,
    .product-view .product-sidebar .product-info-shipping,
    .product-view .product-sidebar .product-info-rewards,
    .promo-banner .promo-icon-one,
    .promo-banner .promo-icon-two,
    .promo-banner .promo-icon-three,
    .website-header .header-bottom .wishlist .wishlist-icon,
    .website-header .header-bottom .cart .cart-icon,
    .website-header.default .header-container  .logo-container,
    .sidebar .sidebar-triangle,
    .ajaxcart-checkout-link,
    .ajaxcart-continue-link,
    .big-shopping-cart,
    .slider-items .btn-cart-icon,    
    footer .footer-top .footer-newsletter .newsletter-subscribe .newsletter-icon
    {
        background-color: <?php echo $css_color1; ?>; 
    }
    
    .customer-account-forgotpassword .main-container .account-forgotpassword,
    .customer-account-create .main-container .account-create,
    .customer-account-login .main-container .account-login,
    .data-table thead,
    .website-header .header-bottom .cart .cart-content,
    .website-header .header-bottom .wishlist .wishlist-content,
    .checkout-cart-index .header-image,
    .checkout-onepage-index .header-image,
    .cart .totals,
    .opc .active .step-title,
    #tabs .product-tab.active,
    .ajaxcart-result, 
    .ajaxcart-loading
    {
        border-color: <?php echo $css_color1; ?>; 
    }   
    
    .form-list label.required em,
    .toolbar .pager .pages .current,
    .website-header .header-bottom .cart .dropdown-content .subtotal-sum,
    .mini-products-list .product-sku span,
    .mini-products-list .product-qty span,
    .website-header .form-currency .current,
    .website-header .form-language .current,
    .website-header .header-bottom .cart .cart-counter:hover,
    .nav-container #nav li a:hover,
    .nav-container #nav li.over a,
    .nav-container #nav li.active a,
    .nav-container #nav ul li a:hover,
    .nav-container #nav ul li.active > a,
    .nav-container #nav ul li.over > a,    
    .nav-container #nav ul li.over > a,    
    .breadcrumbs .breadcrumbs-last,
    #main ul.subsection_tabs li.tab-item a.active
    {
        color: <?php echo $css_color1; ?>; 
    }    
    
    
    /* SECOND COLOR*/
     button.button span,
    .button.view-cart span,
    .promo-sale,
    .navigation-buttons button.scroll-left span
    {
        background-color: <?php echo $css_color2; ?>; 
    }
    .view-more-link
    {
        color: <?php echo $css_color2; ?>; 
    }
    
    
    /* THIRD COLOR*/
    .promo-new,
    .product-shop button.button span,
    .cart .btn-proceed-checkout span,
    .buttons-set button.button span,
    .products-grid .product-item-detailed .price-box{
        background-color: <?php echo $css_color3; ?>; 
    }
    .special-price,
    .price-box
    {
        color: <?php echo $css_color3; ?>; 
    }
    
</style>