<?php
/**
 * 
 * @category  design
 * @package   insale_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php $collection = $this->getReviews(); ?>
<?php if(count($collection)): ?>
<div class="widget-reviews">
        <section class="block-content iosSlider-reviews">
            <ul class="review-slider-items">
                <?php foreach ($collection as $_item): ?>
                    <li class="item">
                        <div class="review-item">
                            <div class="review-top">
                            </div>
                            <div class="review-content">
                                <a class="product-image" 
                                   href="<?php echo $_item->getProductUrl() ?>" 
                                   title="<?php echo $this->htmlEscape($_item->getName()) ?>">
                                    <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50,61); ?>" 
                                         alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
                                </a>      
                                <p class="author-name"> <?php echo $_item->getNickname() ?> </a></p>
                                <p class="product-name"> <a href="<?php echo $_item->getProductUrl() ?>" 
                                        title="<?php echo $this->htmlEscape($_item->getName()) ?>">
                                       <?php echo $this->htmlEscape($_item->getName()) ?> 
                                    </a>
                                </p>        

                                <div class="rating-box">
                                    <div style="width: <?php echo $_item->getRatingSummary()->getData('rating_summary'); ?>%;" class="rating"></div>
                                </div>    

                                <div class="review-short">
                                    <?php 
                                        $_text = $_item->getDescription();
                                        if (strlen($_text) > 130 ) {
                                            $_text = substr($_item->getDescription(),0,130) . ' ...';
                                        } 
                                        echo $_text
                                    ?>
                                </div>                                
                            </div>
                            <div class="review-bottom">
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul> 
        </section>
</div>
<?php endif ?>

