<?php
/**
 * 
 * @category  design
 * @package   insale_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php $upsell_count = count($this->getItemCollection()->getItems()); ?>
<?php if($upsell_count): ?>
<section class="box-collateral box-up-sell">
    
    <header class="grid_4 alpha">
        <div class="upseller-info">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_upsell')->toHtml(); ?>

        <?php if ($upsell_count >3): ?>                            
            <nav class="navigation-buttons">
                <button type="button" class="button scroll-left"><span><span><?php echo $this->__('Scroll Left') ?></span></span></button>
                <button type="button" class="button scroll-right"><span><span><?php echo $this->__('Scroll Right') ?></span></span></button>   
            </nav>    
        <?php endif; ?>   
        </div>    
    </header>
    
    <div class="grid_12 alpha">
        <div id="upsell-container" class="iosSlider-upsell">
            <ul class="slider-items">
                <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
                <?php $this->resetItemsIterator() ?>
                <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                    <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                        <?php if($_link=$this->getIterableItem()): ?>
                            <li class="item">                
                                <div class="product-item">      
                                    
                                    <?php 
                                        $_gallery = Mage::getModel('catalog/product')->load($_link->getId())->getMediaGalleryImages();
                                        $_image = null;
                                        if (count($_gallery)) {
                                            foreach ($_gallery as $item)
                                            {
                                                $_image = $item->getFile();
                                            }     
                                        }
                                    ?>                                    
                                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(260,320) ?>" 
                                             alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                                        <img class="hover-image" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image',$_image)->resize(260,320) ?>" 
                                             alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />                                        
                                    </a>
                                    <a href="#" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>');" class="btn-cart btn-cart-icon">#</a>

                                    <div class="promo-container">
                                        <?php 
                                            $_promo = $this->helper('insale/data')->getPromoLabels($_link);
                                            echo $_promo['sale'];                        
                                            echo $_promo['new'];                        
                                        ?>   
                                    </div>                                      
                                    <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>

                                    <div class="product-name-divider">
                                        <div class="divider-line"></div>
                                        <div class="divider-diamond"></div>
                                    </div>   

                                    <?php if($_link->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_link, 'short') ?>
                                    <?php endif; ?>                    
                                    <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                                </div> 
                            </li>                        
                        <?php endif ?>     
                    <?php endfor; ?>
                <?php endfor; ?>
            </ul>
        </div>
    </div>
</section>
<?php endif ?>
